name: Dependency review

on:
  pull_request:
    branches: ["master", "main"]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - name: Reject vulnerable dependency changes
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48
        with:
          fail-on-severity: moderate
          license-check: true
          deny-licenses: AGPL-1.0-only, AGPL-1.0-or-later, SSPL-1.0
